experiment_name: 'cliv'
output_path: '/home/mperkonigg/Documents/experiments/run_outputs'
matmul_precision: 'medium'

datamodule:
    +class: cliv.datasets.ClivMMISDataModule
    data_path: '/home/mperkonigg/data/MMIS/MMIS2024TASK1/'
    train_path: 'training'
    train_masks: ['label_a1']
    val_path: 'validation'
    val_masks: ['label_a1']
    test_path: 'validation'
    test_masks: ['label_a1']
    traintransforms:
        +class: monai.transforms.Compose
        transforms:
        - +class: monai.transforms.ToTensord
          keys: ['t1c', 't1', 't2', 'label']
        - +class: monai.transforms.EnsureChannelFirstd
          keys: ['t1c', 't1', 't2', 'label']
          channel_dim: 'no_channel'
        - +class: monai.transforms.RandAxisFlipd
          keys: ['t1c', 't1', 't2', 'label']
          prob: 0.5
        - +class: monai.transforms.RandGaussianSmoothd
          keys: ['t1c', 't1', 't2']
          sigma_x: [0.25, 2.0]
          sigma_y: [0.25, 2.0]
          prob: 0.8
        - +class: monai.transforms.RandAffined
          scale_range: [-.1, .1]
          translate_range: [-20, 20]
          shear_range: [-5, 5]
          rotate_range: [-180, 180]
          prob: 0.5
          keys: ['t1c', 't1', 't2', 'label']
        - +class: monai.transforms.CastToTyped
          keys: ['label']
          dtype: 'long'
        - +class: monai.transforms.ScaleIntensityd
          keys: ['t1c', 't1', 't2']
          minv: 0.0
          maxv: 1.0
        - +class: monai.transforms.ResizeWithPadOrCropd
          keys: ['t1c', 't1', 't2', 'label']
          spatial_size: [32, 192, 192]
        - +class: monai.transforms.ConcatItemsd
          keys: ['t1c', 't1', 't2']
          name: 'img'
    valtransforms: &defaults
        +class: monai.transforms.Compose
        transforms:
        - +class: monai.transforms.ToTensord
          keys: ['t1c', 't1', 't2', 'label']
        - +class: monai.transforms.EnsureChannelFirstd
          keys: ['t1c', 't1', 't2', 'label']
          channel_dim: 'no_channel'
        - +class: monai.transforms.CastToTyped
          keys: ['label']
          dtype: 'long'
        - +class: monai.transforms.ScaleIntensityd
          keys: ['t1c', 't1', 't2']
          minv: 0.0
          maxv: 1.0
        - +class: monai.transforms.ResizeWithPadOrCropd
          keys: ['t1c', 't1', 't2', 'label']
          spatial_size: [32, 192, 192]
        - +class: monai.transforms.ConcatItemsd
          keys: ['t1c', 't1', 't2']
          name: 'img'
    testtransforms:
        *defaults
    num_workers: 8
    batch_size: 4

experiment:
    +class: cliv.models.ClivLightningModule
    model:
        +class: cliv.models.ClivModel
        annotators: ['label_a1']
        no_head_layers: 3
        num_classes: 2
        spatial_axes: [2, 3, 4]
        seg_model: 
          +class: monai.networks.nets.UNet
          spatial_dims: 3 
          in_channels: 3
          out_channels: 16
          channels: [64, 128, 256, 512]
          strides: [2, 2, 2, 2]
          num_res_units: 2

    loss:
        +class: msig_tools.ml_framework.losses.CESegLoss

    optimizer: 
       opt_class: 'adam'
       lr: 1e-4
       weight_decay: 0.1
       z_learning_rate: 0.05
    
checkpoint:
    monitor: 'val_loss'
    save_top_k: 1
    mode: 'min'

trainer:
    max_epochs: 100

logger:
    type: 'mlflow'
    tracking_uri: "file:/home/mperkonigg/Documents/experiments/mlflow/"