experiment_name: 'cliv'
output_path: '</path/to/output/>'
matmul_precision: 'medium'

datamodule:
    +class: cliv.datasets.ClivDataModule
    dataset: "QUBIQ"
    data_path: '</path/to/dataset>'
    train_path: "training_data_v3_QC/prostate/Training/"
    train_masks: ['seg01']
    val_path: "validation_data_v3_QC/prostate/Validation/"
    val_masks: ['seg01']
    test_path: "validation_data_v3_QC/prostate/Validation/"
    test_masks: ['seg01']
    traintransforms:
        +class: monai.transforms.Compose
        transforms:
        - +class: monai.transforms.ToTensord
          keys: ['img', 'label']
        - +class: monai.transforms.RandAxisFlipd
          keys: ['img', 'label']
          prob: 0.5
        - +class: monai.transforms.RandGaussianSmoothd
          keys: ['img']
          sigma_x: [0.25, 2.0]
          sigma_y: [0.25, 2.0]
          prob: 0.8
        - +class: monai.transforms.RandAffined
          scale_range: [-.1, .1]
          translate_range: [-20, 20]
          shear_range: [-5, 5]
          rotate_range: [-180, 180]
          prob: 0.5
          keys: ['img', 'label']
        - +class: monai.transforms.CastToTyped
          keys: ['label']
          dtype: 'float'
        - +class: monai.transforms.ScaleIntensityd
          keys: ['img']
          minv: 0.0
          maxv: 1.0
        - +class: monai.transforms.CenterSpatialCropd
          keys: ['img', 'label']
          roi_size: [640, 640]
    valtransforms: &defaults
        +class: monai.transforms.Compose
        transforms:
        - +class: monai.transforms.ToTensord
          keys: ['img', 'label']
        - +class: monai.transforms.CastToTyped
          keys: ['label']
          dtype: 'float'
        - +class: monai.transforms.ScaleIntensityd
          keys: ['img']
          minv: 0.0
          maxv: 1.0
        - +class: monai.transforms.CenterSpatialCropd
          keys: ['img', 'label']
          roi_size: [640, 640]
    testtransforms:
        *defaults
    num_workers: 4
    batch_size: 8

experiment:
    +class: cliv.models.ClivLightningModule
    model:
        +class: cliv.models.ClivModel
        annotators: ['seg01']
        no_head_layers: 3
        num_classes: 2
        spatial_axes: [2, 3]
        seg_model: 
          +class: monai.networks.nets.UNet
          spatial_dims: 2
          in_channels: 1
          out_channels: 16
          channels: [64, 128, 256, 512]
          strides: [2, 2, 2, 2]
          num_res_units: 2

    loss:
        +class: torch.nn.BCEWithLogitsLoss

    optimizer: 
       opt_class: 'adam'
       lr: 1e-4
       weight_decay: 0.1
       z_learning_rate: 0.05
    
checkpoint:
    monitor: 'val_loss'
    save_top_k: 1
    mode: 'min'

trainer:
    max_epochs: 100

logger:
    type: 'mlflow'
    tracking_uri: "file:<path/for/mlflow>" #or uri if running remotley